/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("io.freefair.lombok") version "8.6"
    `maven-publish`
}

dependencies {
    compileOnly(libs.s3);
    compileOnly(libs.crt);
    compileOnly(project(":common"))

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.junit.jupiter)
    testImplementation(libs.s3);
    testImplementation(libs.crt);
    testImplementation(project(":common"))
    testRuntimeOnly(libs.junit.jupiter.launcher)
}

tasks.test {
    environment("AWS_REGION", "eu-west-1")
}

publishing {
    publications {
        create<MavenPublication>("objectClient") {
            // TODO: update this when we figure out versioning
            //  ticket: https://app.asana.com/0/1206885953994785/1207481230403504/f
            version = "1.0.0"

            from(components["java"])
        }
    }
}
